STORAGE_ACCOUNT_NAME = "your-storage-account-name"
DELTA_LAKE_ROOT_PATH = "" # Optional, the root path up until the delta lake catalog
AZURE_TENANT_ID = "your-tenant-id"
AZURE_CLIENT_ID = "your-service-principal-clientid"
AZURE_CLIENT_SECRET = "your-service-principal-secret"